### ISSUE TITLE
Sorry but I wonder how to train my dataset?

### ISSUE THREAD

**Issue by moersxm** [ouyanghaodong/DEYO#6]

**Comment by ouyanghaodong** [comment]
https://docs.ultralytics.com/zh/datasets/#contribute-new-datasets

**Comment by moersxm** [comment]
> https://docs.ultralytics.com/datasets/#contribute-new-datasets Our data format is consistent with YOLOv8, and it is easy to find information online on how to customize a custom dataset.

thanks
